### ISSUE TITLE
Missing null pointer check when removing an attribute

### ISSUE THREAD

**Issue by bergander** [hazelcast/hazelcast-wm#60]
`entry.setDirty(false)` was recently added to HazelcastHttpSession (row 203), but I'm guessing that `entry` can be null since there's a null check above. But the new line is missing a null check.

```
public void removeAttribute(final String name) {
        LocalCacheEntry entry = localCache.get(name);
        if (entry != null && entry != WebFilter.NULL_ENTRY) {
            entry.setValue(null);
            entry.setRemoved(true);
            entry.setDirty(true);
            entry.setReload(false);
        }
        if (!deferredWrite) {
            try {
                webFilter.getClusteredSessionService().deleteAttribute(id, name);
                entry.setDirty(false);
            } catch (Exception e) {
                LOGGER.warning("Unexpected error occurred.", e);
            }
        }
    }
```

This can cause NPE like this:
```
15-Sep-2017 14:38:40.503 VARNING [ajp-nio-8009-exec-10] com.hazelcast.web.HazelcastHttpSession.null Unexpected error occurred.
 java.lang.NullPointerException
	at com.hazelcast.web.HazelcastHttpSession.removeAttribute(HazelcastHttpSession.java:203)
	at org.apache.jasper.runtime.PageContextImpl.doRemoveAttribute(PageContextImpl.java:396)
	at org.apache.jasper.runtime.PageContextImpl.removeAttribute(PageContextImpl.java:377)
	at org.apache.jasper.runtime.JspContextWrapper.removeAttribute(JspContextWrapper.java:226)
	at org.apache.taglibs.standard.tag.common.core.SetSupport.exportToVariable(SetSupport.java:188)
	at org.apache.taglibs.standard.tag.common.core.SetSupport.doEndTag(SetSupport.java:84)
```

**Comment by emre-aydin** [comment]
Hi @bergander 
Thanks for reporting the issue. Here's the PR for fixing it: https://github.com/hazelcast/hazelcast-wm/pull/61 It will be fixed in our next release.
